version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: "bitnami/sqlite:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - sqlite-data:/bitnami/sqlite/data

volumes:
  sqlite-data:
